FROM python:3.8-slim
WORKDIR /app
COPY common/ common/
COPY client_side/ client_side/
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONPATH "${PYTHONPATH}:/app/common:/app/client_side"
CMD ["python", "client_side/client.py"]
