version: '3.8'
services:
  app:
    build: .
    ports:
      - "65432:65432"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: server_client
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
