FROM python:3.8-slim
WORKDIR /app
COPY common/ common/
COPY server_side/ server_side/
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONPATH "${PYTHONPATH}:/app/common:/app/server_side"
CMD ["python", "server_side/server.py"]
EXPOSE 8000
